services:

  - name: frontend
    path: frontend
    language: nodejs
    ecrRepo: travel-booking-frontend

  - name: user-service
    path: user-service
    language: golang
    ecrRepo: travel-booking-user-service

  - name: search-service
    path: search-service
    language: golang
    ecrRepo: travel-booking-search-service

  - name: booking-service
    path: booking-service
    language: golang
    ecrRepo: travel-booking-booking-service

  - name: payment-service
    path: payment-service
    language: golang
    ecrRepo: travel-booking-payment-service

  - name: notification-service
    path: notification-service
    language: golang
    ecrRepo: travel-booking-notification-service