services:

  - name: frontend
    path: frontend
    language: nodejs
    ecrRepo: prod-travelbooking-frontend

  - name: user-service
    path: user-service
    language: golang
    ecrRepo: prod-travelbooking-user-service

  - name: search-service
    path: search-service
    language: golang
    ecrRepo: prod-travelbooking-search-service

  - name: booking-service
    path: booking-service
    language: golang
    ecrRepo: prod-travelbooking-booking-service

  - name: payment-service
    path: payment-service
    language: golang
    ecrRepo: prod-travelbooking-payment-service

  - name: notification-service
    path: notification-service
    language: golang
    ecrRepo: prod-travelbooking-notification-service