apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/10ajaykumar/travel-booking-gitops.git
    targetRevision: main
    path: infra
    helm:
      releaseName: infra
      valueFiles:
        - ../../environments/dev/infra/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: travel-booking-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
