apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/10ajaykumar/travel-booking-gitops.git
    targetRevision: main
    path: charts/search-service
    helm:
      releaseName: search-service
      valueFiles:
        - ../../environments/prod/search-service/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: travel-booking-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
