replicaCount: 2
image:
  repository: 041124309752.dkr.ecr.us-east-1.amazonaws.com/travel-booking-frontend
  tag: "staging-placeholder"
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
