{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.database.name }}
  labels:
    app.kubernetes.io/name: infra
    app.kubernetes.io/part-of: travel-booking
type: Opaque
stringData:
  username: {{ .Values.secrets.database.username | quote }}
  password: {{ .Values.secrets.database.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.jwt.name }}
  labels:
    app.kubernetes.io/name: infra
    app.kubernetes.io/part-of: travel-booking
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwt.value | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.smtp.name }}
  labels:
    app.kubernetes.io/name: infra
    app.kubernetes.io/part-of: travel-booking
type: Opaque
stringData:
  host: {{ .Values.secrets.smtp.host | quote }}
  username: {{ .Values.secrets.smtp.username | quote }}
  password: {{ .Values.secrets.smtp.password | quote }}
{{- end }}
